/**
 * Generate themes/light.css and themes/dark.css from the semantic tokens.
 *
 * Run via:  pnpm --filter @ehrax/design-system generate:css
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildPrimitiveCssVars,
  buildSemanticCssVars,
  renderCssBlock,
} from "../src/themes/css-vars";
import { darkSemantic } from "../src/tokens/semantic/dark";
import { lightSemantic } from "../src/tokens/semantic/light";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "..", "src", "themes");

const HEADER = "/* AUTO-GENERATED by scripts/generate-css.ts — do not edit by hand. */\n\n";

const lightCss =
  HEADER +
  renderCssBlock(":root, [data-theme='light']", {
    "color-scheme": "light",
    ...buildPrimitiveCssVars(),
    ...buildSemanticCssVars(lightSemantic),
  }) +
  "\n";

const darkCss =
  HEADER +
  renderCssBlock("[data-theme='dark']", {
    "color-scheme": "dark",
    ...buildSemanticCssVars(darkSemantic),
  }) +
  "\n";

writeFileSync(join(OUT_DIR, "light.css"), lightCss);
writeFileSync(join(OUT_DIR, "dark.css"), darkCss);

console.log("✓ themes/light.css");
console.log("✓ themes/dark.css");
